### ISSUE TITLE
nodester app init fails

### ISSUE THREAD

**Issue by achegedus** [nodester/nodester-cli#16]
I'm able to create a new app:

``` terminal
NodesterTemp adamh$ nodester app create achtestnode
nodester info creating app: achtestnode server.js
nodester info successfully created app achtestnode to will run on port 10452 from server.js
nodester info run nodester app init achtestnode to setup this app.
```

But when I try to run init, I get this error:

``` terminal
NodesterTemp adamh$ nodester app init achtestnode
nodester info initializing git repo for achtestnode into folder achtestnode
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/adamhegedus/2299-d31184cf64599f6cb45b3555196f8f8f.git achtestnode
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'achtestnode/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:575:15)
    at Object.writeApp (/Users/adamh/local/node/lib/node_modules/nodester-cli/lib/config.js:54:8)
    at /Users/adamh/local/node/lib/node_modules/nodester-cli/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:160:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:246:12)
```

I'm not sure what could be happening here.  Any suggestions?

Thanks,
Adam

**Comment by yocontra** [comment]
Forgot to mention that I fixed this. Update to the latest CLI
