### ISSUE TITLE
User Setup URL 'undefined'

### ISSUE THREAD

**Issue by kevinohara80** [nodester/nodester-cli#31]
When I run...

``` bash
$ nodester user setup my@email.com password
```

I get this

``` bash
nodester info verifying credentials

/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/vendor/cookie/index.js:45
    : url.parse(req.url).pathname;
                   ^
TypeError: Cannot read property 'url' of undefined
    at new Cookie (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/vendor/cookie/index.js:45:20)
    at /usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:432:33
    at Array.forEach (native)
    at Request.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:426:46)
    at Request.emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nodester-cli/node_modules/nodester-api/node_modules/request/main.js:391:16)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1213:22)
    at CleartextStream._push (tls.js:291:27)
```

Running node v0.4.7.

Any ideas?

**Comment by yocontra** [comment]
Ah it looks like the people who made 'request' updated something. We lazily specified the version to *. I'm starting from scratch on a new CLI and won't be using request, it will be out soon. Sorry for the inconvenience

**Comment by yocontra** [comment]
Can you confirm this is still an issue?

**Comment by kevinohara80** [comment]
Good to go. Thanks!
