### ISSUE TITLE
Error on "nodester apps list"

### ISSUE THREAD

**Issue by Fabryz** [nodester/nodester-cli#5]
```
fabryz@fabryz-laptop ~ $ nodester apps list
Name            Port  gitrepo                                                                                     Start         Running    

/usr/local/lib/node/.npm/nodester-cli/0.1.7/package/bin/nodester.js:104
  if (len + 1 >= str.length) {
                    ^
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node/.npm/nodester-cli/0.1.7/package/bin/nodester.js:104:21
    at /usr/local/lib/node/.npm/nodester-cli/0.1.7/package/bin/nodester.js:223:127
    at Object.callback (/usr/local/lib/node/.npm/nodester-api/0.1.4/package/nodester.js:42:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/request/1.2.0/package/main.js:176:44)
    at IncomingMessage.emit (events.js:59:20)
    at HTTPParser.onMessageComplete (http.js:111:23)
    at Client.onData [as ondata] (http.js:1433:27)
    at Client._onReadable (net.js:654:27)
    at IOWatcher.onReadable [as callback] (net.js:156:10)
```

Node version v0.5.0-pre

**Comment by davglass** [comment]
Can you try it with the latest CLI?
`npm install nodester-cli@0.2.3`

**Comment by Fabryz** [comment]
Damn, I didn't have the latest version of nodester-cli.

It doesn't give any error with the 0.2.3, thanks.
