### ISSUE TITLE
Error: npm doesn't work with node v0.8.1

### ISSUE THREAD

**Issue by ghost** [nodester/nodester-cli#50]
I tried `nodester npm list nodedemo`, outputs:

```
nodester info list npm packages for app: nodedemo
nodester Error: npm doesn't work with node v0.8.1
```

Can somebody tell me what is going on ? Thanks.

**Comment by jaydeepw** [comment]
I can confirm this bug.

I am developing a basic real-time communication app using nodeJS.
I simply tried installing ExpressJS on nodester.
It failed to install it.

jay@jayslaptop:~/git-projects/realtime$ nodester npm install express jade
nodester info installing to app: realtime
nodester info installing these npm packages: express,jade
nodester Error: npm doesn't work with node v0.8.1
nodester Required: node@0.4 || 0.5 || 0.6
nodester     at /usr/lib/node_modules/npm/bin/npm-cli.js:57:23
nodester     at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:77:3)
nodester     at Module._compile (module.js:449:26)
nodester     at Object.Module._extensions..js (module.js:467:10)
nodester     at Module.load (module.js:356:32)
nodester     at Function.Module._load (module.js:312:12)
nodester     at Module.runMain (module.js:487:10)
nodester     at process.startup.processNextTick.process._tickCallback (node.js:244:9) 

nodester warn you should restart your app after you are finished installing packages.

**Comment by alejandro** [comment]
This is a common problem when nodester can't read your package.json. So it picks the lowest version available. It should work now, though. We've upgraded most of our stack to 0.8.x.

**Comment by jaydeepw** [comment]
I can confirm that it is working fine now.

Now I am facing another problem.
I am using express in my application. I runs well locally, but when I upload it to the server,
I am getting error in logs that the address is already in use.

I tried searching a bit on finding the ip address on which my app is hosted on nodester, could not get any help

Could you give me some pointers.

**Comment by alejandro** [comment]
That's weird. try to print `process.env.app_port` and see if it is the same as the one that `nodester app info appname` gives you.

**Comment by jaydeepw** [comment]
process.env.app_port this gives me the port. No issues with this, the issue is with the ip address of my app on nodester.

**Comment by alejandro** [comment]
Why you would need to setup the address? just point it to 127.0.0.1 and it should just work. What's the port to check in my side?

**Comment by jaydeepw** [comment]
The app name is 'realtime' and its running on port 19855

**Comment by jaydeepw** [comment]
as it is working on my local machine with 127.0.0..1, by default it must be taking it. So consequently it should work on nodester also. But it is not.

Following are the logs of the app running on nodester.

Process died with exit code 1. Restarting...
Spawing /app/server.js
WARN :: You are running in node-0.4.9. You might want to upgrade to node-v0.6.17
Running node v-0.4.9

node.js:134

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

Error: EADDRINUSE, Address already in use
    at Server._doListen (net.js:1100:5)
    at net.js:1071:14
    at Object.lookup (dns.js:159:5)
    at Server.listen (net.js:1065:20)
    at Object.<anonymous> (/app/server.js:31:24)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)

**Comment by alejandro** [comment]
BTW what are the logs?

**Comment by jaydeepw** [comment]
I have copied them in the comment above.

**Comment by alejandro** [comment]
Did you output the port? Probably is not picking the right port. Also add to your package.json the latest node version or at least the 0.6.x one

**Comment by jaydeepw** [comment]
no, I will do it in the evening and update you with it.
Thanks for the help.

**Comment by jaydeepw** [comment]
Hi alejandromg,

   I think we have found the problem. It seems that server is not returning appropriate port on which the app is running.
Take a look at the logs. Port seems to be undefined when I try to print process.env.PORT

Process died with exit code 1. Restarting...
Spawing /app/server.js
WARN :: You are running in node-0.4.9. You might want to upgrade to node-v0.6.17
Running node v-0.4.9

--------------------------TAKE A LOOK HERE--------------------
App Running on: undefined

node.js:134

```
    throw e; // process.nextTick error, or 'error' event on first tick
```

^

Error: EADDRINUSE, Address already in use
    at Server._doListen (net.js:1100:5)
    at net.js:1071:14
    at Object.lookup (dns.js:159:5)
    at Server.listen (net.js:1065:20)
    at Object.<anonymous> (/app/server.js:34:24)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)

Error: Restarted too many times, bailing.
nodester info ok!

**Comment by jaydeepw** [comment]
Let me know if can help you with anything else, for now I am hardcoding the PORT number in the app.

When I run the app with the PORT number hardcoded, I get 500 Internal server error

http://realtime.nodester.com/index.html

try it.

**Comment by alejandro** [comment]
And that's the problem... We don't use process.env.PORT instead we use process.env.app_port. 

Cheers

**Comment by jaydeepw** [comment]
ok fine, what about the internal server error that I am getting for the app now.

**Comment by alejandro** [comment]
Which one? The npm doesn't work with 0.8.x ?  You need to update your package.json with a new version...

**Comment by jaydeepw** [comment]
No, app_port is working fine.

I installed Express and dependencies required for exp. on nodester.

When I run the app locally, it works fine, but on the server it is crashing.
Here are the logs. I tried searching a bit for it, but sadly could not come up with anything.

New PID: 2288
chroot_runner
chroot_runner
Spawing /app/server.js
WARN :: You are running in node-0.4.9. You might want to upgrade to node-v0.6.17
Running node v-0.4.9
App Running on: 19855

Express server listening on port 19855

TypeError: Object #<SendStream> has no method 'on'
    at Object.static [as handle](/app/node_modules/express/node_modules/connect/lib/middleware/static.js:76:8)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at pass (/app/node_modules/express/lib/router/index.js:111:24)
    at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:4)
    at Object.router [as handle](/app/node_modules/express/lib/router/index.js:33:10)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle](/app/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/app/node_modules/express/node_modules/connect/lib/middleware/multipart.js:52:61)
    at /app/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9

Error: Can't use mutable header APIs after sent.
    at ServerResponse.getHeader (http.js:544:11)
    at /app/node_modules/express/node_modules/connect/lib/middleware/logger.js:230:26
    at ServerResponse.<anonymous> (/app/node_modules/express/node_modules/connect/lib/middleware/logger.js:150:20)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at pass (/app/node_modules/express/lib/router/index.js:111:24)
    at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:4)
    at Object.router [as handle](/app/node_modules/express/lib/router/index.js:33:10)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle](/app/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)

nodester info ok!

**Comment by alejandro** [comment]
Try to upgrade to 0.8.x. The current express version is 3.0.0pre which is not compatible with old versions. Probably that's why...

**Comment by jaydeepw** [comment]
Ohh..is there a way to update nodeJS version on nodester?

how do I do that?

**Comment by chrismatthieu** [comment]
Checkout http://blog.nodester.com/post/26237056445/nodester-running-node-js-0-8-1

**Comment by jaydeepw** [comment]
Thanks a ton, updating nodeJS version in the package fixed it.

Now I can use realtime.nodester.com

**Comment by chrismatthieu** [comment]
Nice app name!

**Comment by jaydeepw** [comment]
hahaha...thanks.

I am building realtime analytics using websockets, express and nodejs.
