### ISSUE TITLE
Cannot setup nodester user

### ISSUE THREAD

**Issue by ssbanerje** [nodester/nodester-cli#54]
Hi,
I am trying to use nodester-cli to set up my nodester account on my laptop

I am using the command

```
nodester user setup subszero <pass>
```

to try and setup this account on my computer. But this is always giving me this error ---

```
/usr/local/share/npm/lib/node_modules/nodester-cli/lib/config.js:71
    auth += c.final("utf8");
              ^
TypeError: DecipherFinal fail
    at decryptAuth (/usr/local/share/npm/lib/node_modules/nodester-cli/lib/config.js:71:15)
    at Object.exports.parse (/usr/local/share/npm/lib/node_modules/nodester-cli/lib/config.js:165:13)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/nodester-cli/lib/commands.js:58:21)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/nodester-cli/bin/nodester.js:11:11)
```

I couldn't really find much on this error on the net. Could you guys tell me what is going wrong here?

**Comment by gkoberger** [comment]
Possibly fixed by #56?
