### ISSUE TITLE
CLI Coupon Request Fails (REST API Works)

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester-cli#8]
nodester coupon chris@matthieu.us
nodester info Requesting coupon code for: chris@matthieu.us

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
ReferenceError: config is not defined
    at Object.run (/usr/local/lib/node/.npm/nodester-cli/0.2.8/package/lib/coupon.js:17:56)
    at Object.run (/usr/local/lib/node/.npm/nodester-cli/0.2.8/package/lib/commands.js:101:27)
    at Object.<anonymous> (/usr/local/lib/node/.npm/nodester-cli/0.2.8/package/bin/nodester.js:8:5)
    at Module._compile (module.js:373:26)
    at Object..js (module.js:379:10)
    at Module.load (module.js:305:31)
    at Function._load (module.js:271:10)
    at require (module.js:317:19)
    at Object.<anonymous> (/usr/local/bin/nodester@0.2.8:11:18)
    at Module._compile (module.js:373:26)

curl -X POST -d "email=chris@matthieu.us" http://nodester.com/coupon
{"status":"success - you are now in queue to receive an invite on our next batch!"}

**Comment by davglass** [comment]
Fixed: 01c66941272be76acc31aca432fb25b3b3502f82
